### ISSUE TITLE
Show hidden files

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/tcet-linux-settings#1] opened 2023-04-22 19:31 UTC
Show hidden files doesn't work

**Comment by Akash6222** [comment] 2023-04-24 20:17
In my case it works

**Comment by Akash6222** [comment] 2023-05-20 06:55
Ohh got it after right click inside the thunar file manager , the show hidden file button doesn't work.

**Comment by Akash6222** [comment] 2023-05-20 06:57
The root cause is that xdotool package is installed.

**Comment by Akash6222** [comment] 2023-05-20 06:58
Closing this issue and creating new issue on tcet-linux repo

**Closed** 2023-05-20 07:00 UTC
